'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {CheckCircle2,ChevronLeft,ChevronRight,LoaderCircle} from 'lucide-react';
type Q={id:number;question:string;options:string[]};
export default function Exam(){const router=useRouter();const [qs,setQs]=useState<Q[]>([]);const [answers,setAnswers]=useState<Record<number,string>>({});const [i,setI]=useState(0);const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState('');
useEffect(()=>{fetch('/api/questions',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load');setQs(d.questions);setLoading(false)}).catch(e=>{setError(e.message||'Could not load the assessment. Please refresh.');setLoading(false)})},[]);
if(loading)return <main className="loader-screen"><div><div className="orb-loader"/><h3>Creating your assessment</h3><div className="small">Shuffling questions and answer choices…</div><div className="loader-dots"><i/><i/><i/></div></div></main>;
if(error)return <main className="exam-wrap"><div className="container"><div className="card"><h2>Something went wrong</h2><p className="small">{error}</p><button className="primary" onClick={()=>location.reload()}>Try again</button></div></div></main>;
const q=qs[i];const selected=answers[q.id];
const finish=async()=>{setSubmitting(true);try{const r=await fetch('/api/score',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to score assessment');sessionStorage.setItem('ai_exam_score',String(d.score));sessionStorage.setItem('ai_exam_total',String(d.total));sessionStorage.setItem('ai_exam_passed',String(d.passed));router.push('/certificate')}catch(e:any){setError(e.message||'Unable to submit assessment.');setSubmitting(false)}};
return <main className="exam-wrap"><div className="container"><div className="exam-head"><div><b>AI Skills Assessment</b><div className="qnum">Question {i+1} of {qs.length}</div></div><div className="pill">{Object.keys(answers).length}/{qs.length} answered</div></div><div className="progress"><div style={{width:`${((i+1)/qs.length)*100}%`}}/></div><section className="card"><div className="qnum">{String(i+1).padStart(2,'0')} / {String(qs.length).padStart(2,'0')}</div><div className="question">{q.question}</div>{q.options.map((o)=><button key={o} className={`option ${selected===o?'selected':''}`} onClick={()=>setAnswers(a=>({...a,[q.id]:o}))}><span className="radio"/><span>{o}</span></button>)}<div className="footer-actions">{i>0&&<button className="secondary" onClick={()=>setI(i-1)}><ChevronLeft size={17}/> Back</button>}{i<qs.length-1?<button className="primary" disabled={!selected} onClick={()=>setI(i+1)}>Next <ChevronRight size={17}/></button>:<button className="primary" disabled={!selected||Object.keys(answers).length<qs.length||submitting} onClick={finish}>{submitting?<><LoaderCircle size={17} className="spin"/> Checking…</>:<><CheckCircle2 size={17}/> Submit Assessment</>}</button>}</div>{error&&<div className="toast">{error}</div>}</section></div></main>}
